[package]
name = "simple-merkle-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives = { version = "0.6.2", default-features = false }
alloy-dyn-abi = { version = "0.6.2", default-features = false }
hashbrown = "0.14.3"
anyhow = "1.0"